package net.mammothmkiv.testchat.client;

import com.google.common.eventbus.Subscribe;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import net.mammothmkiv.testchat.client.events.LoginFailedEvent;
import net.mammothmkiv.testchat.client.events.LoginSuccessEvent;
import net.mammothmkiv.testchat.common.AuthenticationCredentials;
import net.mammothmkiv.testchat.common.UserAuthenticationException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class ClientLoginForm {
    private JPanel pnMain;
    private JTextField fNickname;
    private JButton btnSignin;
    private JLabel lbNickname;
    private JTextPane lbError;
    private JFrame frame;

    public ClientLoginForm() {
        ChatCore.getInstance().registerEventHandler(this);
        frame = new JFrame("ClientLoginForm");
        frame.setContentPane(pnMain);
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false);
        btnSignin.addActionListener(this::onLoginButtonClick);
    }

    private void onLoginButtonClick(ActionEvent e) {
        try {
            resetForm();
            ChatCore.getInstance().login(new AuthenticationCredentials(fNickname.getText()));
        } catch (UserAuthenticationException ex) {
            onLoginFailed(new LoginFailedEvent(ex.getMessage()));
        }
    }

    @Subscribe
    public void onLoginSuccess(LoginSuccessEvent e) {
        FormManager.getInstance().hideLoginForm();
        FormManager.getInstance().showChatForm();
        ChatCore.getInstance().requestMemberList();
    }

    @Subscribe
    public void onLoginFailed(LoginFailedEvent e) {
        lbError.setText(e.getMessage());
        lbError.setVisible(true);
    }

    private void resetForm() {
        lbError.setText("");
        lbError.setVisible(false);
    }

    public void dispose() {
        frame.dispose();
    }

    public void show() {
        frame.setVisible(true);
    }

    public void hide() {
        frame.setVisible(false);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnMain = new JPanel();
        pnMain.setLayout(new GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
        pnMain.setAutoscrolls(false);
        pnMain.setMaximumSize(new Dimension(260, -1));
        pnMain.setMinimumSize(new Dimension(260, 135));
        pnMain.setPreferredSize(new Dimension(260, 135));
        pnMain.setRequestFocusEnabled(true);
        fNickname = new JTextField();
        pnMain.add(fNickname, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnSignin = new JButton();
        btnSignin.setText("Sign In");
        pnMain.add(btnSignin, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lbNickname = new JLabel();
        lbNickname.setText("Nickname:");
        pnMain.add(lbNickname, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        pnMain.add(spacer1, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        pnMain.add(spacer2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        pnMain.add(spacer3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(20, -1), null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        pnMain.add(spacer4, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(20, -1), null, null, 0, false));
        lbError = new JTextPane();
        lbError.setBackground(new Color(-1184275));
        lbError.setEditable(false);
        lbError.setOpaque(false);
        lbError.setText("");
        lbError.setVisible(false);
        pnMain.add(lbError, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 0), new Dimension(150, -1), new Dimension(150, -1), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnMain;
    }
}
